config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users

  resources :listings, except: [:index, :destroy] do
    resources :bids, only: [:new, :create]
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing

  default_scope -> { order('bids.created_at DESC') }

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validate :if_bidder_is_not_owner
  validate :if_amount_is_greater
  validate :if_listing_is_active
  # validate :if_bidder_is_not_current

  after_save :update_listing_final_price

  def if_bidder_is_not_owner
    if user.id == listing.user.id
      errors.add(:user, 'cannot bid on own listing')
    end
  end

  def if_amount_is_greater
    current_bid = self.listing.bids.first
    listing_price = self.listing.set_price
    if current_bid && current_bid.amount.to_i > self.amount.to_i
      errors.add(:amount, 'must be higher than current bid')
    elsif current_bid == nil || listing_price.to_i >= self.amount.to_i
      errors.add(:amount, 'must be higher than set price')
    end
  end

  def if_listing_is_active
    errors.add(:amount, 'bidding has ended on this listing') if self.listing.end_date < Time.now
  end

  def if_bidder_is_not_current
    current_bid = self.listing.bids.first
    current_bidder = current_bid.user
    if current_bid && current_bidder.email == self.user.email
      errors.add(:amount, 'you cannot bid twice in a row')
    end
  end

  def update_listing_final_price
    self.listing.update_attribute(:final_price, self.amount)
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :bids

  validates :title, presence: true, length: { maximum: 140 }
  validates :base_price, presence: true, numericality: { only_integer: true }
  validates :end_date, presence: true

  default_scope -> { order('items.created_at DESC') }
  scope :current, -> { where('end_date >= ?', Time.now) }
  scope :ended, -> { where('end_date <= ?', Time.now) }
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  has_many :bids, dependent: :destroy

  enum status: { active: 1, expired: 2 }

  default_scope -> { order('listings.created_at DESC') }
  scope :current, -> { where('end_date >= ?', Time.now) }
  scope :ended, -> { where('end_date <= ?', Time.now) }

  validates :title, presence: true, length: { maximum: 140 }
  validates :set_price, presence: true, numericality: { only_integer: true }
  validates :end_date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :listings, dependent: :destroy
  has_many :bids, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!

  def new
    @bid = Bid.new
  end

  def create
    @listing = Listing.find(params[:listing_id])
    @bid = @listing.bids.new(bid_params)
    @bid.user_id = current_user.id
    if @bid.save
      redirect_to listing_path(@listing), notice: 'Bid saved!'
    else
      redirect_to listing_path(@listing), error: 'Bid cannot be saved'
    end
  end

  private
  def bid_params
    params.require(:bid).permit(:user_id, :listing_id, :amount, :status)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update]

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save
      redirect_to @listing, notice: 'Listing created!'
    else
      render 'new', error: 'Create failed. Try again?'
    end
  end

  def show
    @bid = Bid.new
    @listing_bids = @listing.bids
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to @listing, notice: 'Listing updated!'
    else
      render 'edit', error: 'Update error. Try again?'
    end
  end

  private
  def listing_params
    params.require(:listing).permit(:user_id, :title, :description, :set_price, :final_price, :end_date, :default_image, :status)
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @current_listings = Listing.current
    @ended_listings = Listing.ended
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_alert.html.haml
- if flash[:notice]
  .alert.alert-info.alert-dismissible.alert-notification{role: "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} &times;
    = flash[:notice]
- if flash[:error]
  .alert.alert-danger.alert-dismissible.alert-notification{role: "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} &times;
    = flash[:error]

app/views/items/_item_form.html.haml
= form_for @item do |f|
  - if @item.errors.any?
    %h2
      = pluralize(@item.errors.count, "error")
      prohibited this item from being saved:
    %ul
      - @item.errors.full_messages.each do |msg|
        %li #{msg}

  .form-group
    = f.label :title
    = f.text_field :title, placeholder: 'item title', class: 'form-control'
  .form-group
    = f.label :description
    = f.text_field :description, placeholder: 'item description', class: 'form-control'
  .form-group
    = f.label :base_price
    = f.text_field :base_price, class: 'form-control'
  .form-group
    = f.label :end_date
    = f.datetime_select :end_date, default: Time.now + 1.day, class: 'form-control'
  = f.submit class: 'btn btn-success'
  = link_to 'Back', root_path, class: 'btn btn-default'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AuctionSite
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fluid
      %section{style: 'padding-top: 15px;'}
        = link_to 'AuctionSite', root_path, class: 'btn btn-default btn-lg'
        - if user_signed_in?
          Signed In As: #{current_user.email}
        = render 'alert'
      = yield

app/views/listings/_listing_form.html.haml
= form_for @listing do |f|
  - if @listing.errors.any?
    %h2
      = pluralize(@listing.errors.count, "error")
      prohibited this listing from being saved:
    %ul
      - @listing.errors.full_messages.each do |msg|
        %li #{msg}

  .form-group
    = f.label :title
    = f.text_field :title, placeholder: 'Listing title', class: 'form-control'
  .form-group
    = f.label :description
    = f.text_field :description, placeholder: 'Listing description', class: 'form-control'
  .form-group
    = f.label :set_price
    = f.text_field :set_price, class: 'form-control'
  .form-group
    = f.label :end_date
    = f.datetime_select :end_date, default: Time.now + 1.day, class: 'form-control'
  = f.submit class: 'btn btn-success'
  = link_to 'Back', root_path, class: 'btn btn-default'

app/views/listings/edit.html.haml
.col-md-10.col-md-offset-1
  %h1 Edit #{@listing.title}
  = render 'listing_form'

app/views/listings/new.html.haml
.col-md-10.col-md-offset-1
  %h1 New Listing
  = render 'listing_form'

app/views/listings/show.html.haml
.col-md-10.col-md-offset-1{style: 'margin-bottom: 25px;'}
  %section{style: 'margin-bottom: 25px;'}
    %h1 #{@listing.title}
    %p #{@listing.description}
    %span{style: 'font-size: 14px; font-weight: bold;'} Listed by #{@listing.user.email} on #{@listing.created_at.strftime('%d-%b-%y, %I.%M%P')}
  %p
    Base Price:
    %span{style: 'font-weight: bold;'} MYR #{@listing.set_price}
  %p
    Current Price:
    %span{style: 'font-weight: bold;'} MYR #{@listing.final_price}
    (#{@listing.bids.count} bids)
  - unless @listing.end_date < Time.now
    .form-group
      = form_for @bid, url: listing_bids_path(@listing) do |f|
        .row
          .col-sm-2.col-xs-3
            Place Bid:
          .col-sm-2.col-xs-3
            = f.text_field :amount, placeholder: '1.00', class: 'form-control'
          .col-sm-2.col-xs-2
            = f.submit 'Bid', class: 'btn btn-success'
  %p
    - if @listing.end_date > Time.now
      Time Left:
      %span{style: 'font-weight: bold; color: red;'} #{distance_of_time_in_words(Time.now, @listing.end_date, include_seconds: true)}
    - else
      %span{style: 'font-weight: bold; color: red;'} Ended
    %span{style: 'font-size: 14px;'} (#{@listing.end_date.strftime('%d-%b-%y, %I.%M%P')})
  %section{style: 'margin-top: 25px;'}
    - if @listing_bids.any?
      %p{style: 'font-weight: bold;'} Bids (newest first):
      - @listing_bids.each do |listing_bid|
        %ul
          %li
            %span MYR #{listing_bid.amount} by
            %span{style: 'font-weight: bold;'} #{listing_bid.user.email}
            %span on #{listing_bid.created_at.strftime('%d %b %y, %I.%M%P')}
  %section{style: 'margin-top: 25px;'}
    - if current_user && current_user.id == @listing.user.id
      = link_to 'Edit', edit_listing_path(@listing), class: 'btn btn-warning'
    = link_to 'Back', root_path, class: 'btn btn-default'

app/views/pages/index.html.haml
.row
  %section.col-md-10.col-md-offset-1
    %h1 AuctionSite
    %p Welcome to AuctionSite
    - if user_signed_in?
      = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-warning'
      = link_to 'List Listing', new_listing_path, class: 'btn btn-success'
    - else
      = link_to 'Register', new_user_registration_path, class: 'btn btn-primary'
      = link_to 'Login', new_user_session_path, class: 'btn btn-info'
  %section.col-md-10.col-md-offset-1{style: 'margin-top: 25px; margin-bottom: 25px;'}
    %p{style: 'font-weight: bold;'} Active Listings (newest first):
    - if @current_listings.any?
      - @current_listings.in_groups_of(3) do |group|
        .row
          - group.compact.each do |listing|
            .col-md-4{style: 'padding: 10px; text-align: center;'}
              = link_to listing_path(listing) do
                %article #{image_tag 'default-thumb.gif'}
                %article{style: 'padding-top: 5px;'} #{listing.title}
  %section.col-md-10.col-md-offset-1{style: 'margin-top: 25px; margin-bottom: 25px;'}
    %p{style: 'font-weight: bold;'} Expired Listings (newest first):
    - if @ended_listings.any?
      - @ended_listings.in_groups_of(3) do |group|
        .row
          - group.compact.each do |listing|
            .col-md-4{style: 'padding: 10px; text-align: center;'}
              = link_to listing_path(listing) do
                %article #{image_tag 'default-thumb.gif'}
                %article{style: 'padding-top: 5px;'} #{listing.title}